name: Stop EC2 Instance

on:
  workflow_dispatch:
jobs:
  stop:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Detener instancia EC2
        run: |
          echo "Deteniendo la instancia EC2..."
          aws ec2 stop-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
